core/urls.py
from django.urls import path

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index_view'),
]

employer/company/urls.py
from django.urls import path

from employer.company.views import CompanyCreateView, CompanyDetailView

urlpatterns = [
    path('<slug:slug>/detail/', CompanyDetailView.as_view(), name='company_detail'),
    path('new-company/', CompanyCreateView.as_view(), name='new_company'),
]

jobsportal/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import UserSignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', UserSignupView.as_view(), name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('company/', include('employer.company.urls')),
    path('job/', include('employer.job.urls')),
    path('resume/', include('jobseeker.resume.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employer/company/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse

from core.models import Userprofile


class Company(models.Model):
    amount = [
        ('0 - 9', '0 - 9'),
        ('10 - 99', '10 - 99'),
        ('100 - 999', '100 - 999'),
        ('1,000 - 9,999', '1,000 - 9,999'),
        ('10,000 - 99,999', '10,000 - 99,999'),
        ('100,000 - 999,999', '100,000 - 999,999'),

    ]

    def load_photo(self, file_name):
        file_type = file_name.split(".")[-1]
        file_name = ".".join(['{}/{}_logo', file_type])
        return file_name.format(
            self.name,
            self.name
        )

    name = models.CharField(max_length=75, verbose_name='Название компании')
    employer = models.OneToOneField(Userprofile, related_name='company', null=True, blank=True,
                                    on_delete=models.CASCADE, verbose_name='Работодатель')
    field_of_activity = models.CharField(max_length=75, verbose_name='Сфера деятельности')
    short_description = models.TextField(max_length=400, verbose_name='Краткое описание')
    location = models.CharField(max_length=75, verbose_name='Локация')
    logo = models.ImageField(upload_to=load_photo, default='Default/logo-default.png', null=True, blank=True, verbose_name='Лого')
    created_at = models.CharField(max_length=4, verbose_name='Год создания')
    amount_of_workers = models.CharField(max_length=20, choices=amount, default='10 - 99',
                                         verbose_name='Количество работников')
    phone = models.CharField(max_length=75, verbose_name='Номер телефона')
    website = models.URLField(null=True, blank=True, verbose_name='Адрес вебсайта')
    email = models.EmailField(verbose_name='Почта')
    slug = models.SlugField(max_length=75, unique=True)
    facebook_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на фейсбук компании')
    google_plus_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на гугл+ компании')
    dribbble_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на дрибл компании')
    pinterest_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на пинтерест компании')
    twitter_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на твиттер компании')
    github_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на гитхаб компании')
    instagram_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на инстаграм компании')
    youtube_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на ютуб компании')
    company_detail = RichTextField(blank=True, null=True, verbose_name='Полное описание')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index_view')

employer/company/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, DetailView

from employer.company.models import Company
from django.utils.text import slugify
from django.db import IntegrityError

from employer.job.models import Job
from django.core.exceptions import ObjectDoesNotExist


class CompanyCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'company/company_add.html'
    model = Company
    fields = ['name', 'field_of_activity', 'short_description', 'logo', 'location', 'created_at', 'amount_of_workers',
              'phone', 'website', 'email', 'facebook_url', 'google_plus_url', 'dribbble_url', 'pinterest_url',
              'twitter_url', 'github_url', 'instagram_url', 'youtube_url', 'company_detail']

    def form_valid(self, form):
        form.instance.employer = self.request.user.userprofile
        try:
            form.instance.slug = slugify(form.instance.name)
            return super().form_valid(form)
        except IntegrityError:
            latest_id = form.instance.__class__.objects.last().pk
            form.instance.slug = slugify(f'{form.instance.name}-{latest_id}')
            return super().form_valid(form)

    def test_func(self):
        """ Access is allowed only for Employers without any company """
        user_is_employer = self.request.user.userprofile.is_employer
        self.without_company = None
        if user_is_employer:
            try:
                self.request.user.userprofile.company
            except ObjectDoesNotExist:
                self.without_company = True
            else:
                self.without_company = False
        user = user_is_employer and self.without_company
        return user


class CompanyDetailView(DetailView):
    model = Company
    template_name = 'company/company_detail.html'
    slug_field = 'slug'
    context_object_name = 'company'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company_jobs'] = Job.objects.filter(company=self.object).order_by('-created_at')[:5]
        return context

employer/company/templates/company/company-manage.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Post a job position or create your online resume by TheJobs!">
    <meta name="keywords" content="">

    <title>TheJobs - Manage company</title>

    <!-- Styles -->
    <link href="assets/css/app.min.css" rel="stylesheet">
    <link href="assets/css/thejobs.css" rel="stylesheet">
    <link href="assets/css/custom.css" rel="stylesheet">

    <!-- Fonts -->
    <link href='http://fonts.googleapis.com/css?family=Raleway:100,300,400,500,600,800%7COpen+Sans:300,400,500,600,700,800%7CMontserrat:400,700' rel='stylesheet' type='text/css'>

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/apple-touch-icon.png">
    <link rel="icon" href="assets/img/favicon.ico">
  </head>

  <body class="nav-on-header smart-nav bg-alt">

    <!-- Navigation bar -->
    <nav class="navbar">
      <div class="container">

        <!-- Logo -->
        <div class="pull-left">
          <a class="navbar-toggle" href="#" data-toggle="offcanvas"><i class="ti-menu"></i></a>

          <div class="logo-wrapper">
            <a class="logo" href="index.html"><img src="assets/img/logo.png" alt="logo"></a>
            <a class="logo-alt" href="index.html"><img src="assets/img/logo-alt.png" alt="logo-alt"></a>
          </div>

        </div>
        <!-- END Logo -->

        <!-- User account -->
        <div class="pull-right">

          <div class="dropdown user-account">
            <a class="dropdown-toggle" href="#" data-toggle="dropdown">
              <img src="assets/img/logo-envato.png" alt="avatar">
            </a>

            <ul class="dropdown-menu dropdown-menu-right">
              <li><a href="user-login.html">Login</a></li>
              <li><a href="user-register.html">Register</a></li>
              <li><a href="user-forget-pass.html">Forget pass</a></li>
              <li><a href="#">Logout</a></li>
            </ul>
          </div>

        </div>
        <!-- END User account -->

        <!-- Navigation menu -->
        <ul class="nav-menu">
          <li>
            <a href="index.html">Home</a>
            <ul>
              <li><a href="index.html">Version 1</a></li>
              <li><a href="index-2.html">Version 2</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Position</a>
            <ul>
              <li><a href="job-list-1.html">Browse jobs - 1</a></li>
              <li><a href="job-list-2.html">Browse jobs - 2</a></li>
              <li><a href="job-list-3.html">Browse jobs - 3</a></li>
              <li><a href="job-detail.html">Job detail</a></li>
              <li><a href="job-apply.html">Apply for job</a></li>
              <li><a href="job-add.html">Post a job</a></li>
              <li><a href="job-manage.html">Manage jobs</a></li>
              <li><a href="job-candidates.html">Candidates</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Resume</a>
            <ul>
              <li><a href="resume-list.html">Browse resumes</a></li>
              <li><a href="resume-detail.html">Resume detail</a></li>
              <li><a href="resume-add.html">Create a resume</a></li>
              <li><a href="resume-manage.html">Manage resumes</a></li>
            </ul>
          </li>
          <li>
            <a class="active" href="#">Company</a>
            <ul>
              <li><a href="company-list.html">Browse companies</a></li>
              <li><a href="company-detail.html">Company detail</a></li>
              <li><a href="company-add.html">Create a company</a></li>
              <li><a class="active" href="company-manage.html">Manage companies</a></li>
            </ul>
          </li>
          <li>
            <a href="#">Pages</a>
            <ul>
              <li><a href="page-blog.html">Blog</a></li>
              <li><a href="page-post.html">Blog-post</a></li>
              <li><a href="page-about.html">About</a></li>
              <li><a href="page-contact.html">Contact</a></li>
              <li><a href="page-faq.html">FAQ</a></li>
              <li><a href="page-pricing.html">Pricing</a></li>
              <li><a href="page-typography.html">Typography</a></li>
              <li><a href="page-ui-elements.html">UI elements</a></li>
            </ul>
          </li>
        </ul>
        <!-- END Navigation menu -->

      </div>
    </nav>
    <!-- END Navigation bar -->


    <!-- Page header -->
    <header class="page-header bg-img size-lg" style="background-image: url(assets/img/bg-banner1.jpg)">
      <div class="container no-shadow">
        <h1 class="text-center">Manage companies</h1>
        <p class="lead text-center">Here's the list of your registered companies. You can edit or delete them, or even add a new one.</p>
      </div>
    </header>
    <!-- END Page header -->


    <!-- Main container -->
    <main>
      <section class="no-padding-top bg-alt">
        <div class="container">
          <div class="row item-blocks-condensed">

            <div class="col-xs-12 text-right">
              <br>
              <a class="btn btn-primary btn-sm" href="company-add.html">Add new company</a>
            </div>


            <!-- Company item -->
            <div class="col-xs-12">
              <div class="item-block">
                <header>
                  <a href="company-detail.html"><img src="assets/img/logo-google.jpg" alt=""></a>
                  <div class="hgroup">
                    <h4><a href="company-detail.html">Google</a></h4>
                    <h5>Internet and computer software <a href="company-detail.html#open-positions"><span class="label label-info">15 jobs</span></a></h5>
                  </div>
                  <div class="action-btn">
                    <a class="btn btn-xs btn-gray" href="#">Edit</a>
                    <a class="btn btn-xs btn-danger" href="#">Delete</a>
                  </div>
                </header>
              </div>
            </div>
            <!-- END Company item -->


            <!-- Company item -->
            <div class="col-xs-12">
              <div class="item-block">
                <header>
                  <a href="company-detail.html"><img src="assets/img/logo-facebook.png" alt=""></a>
                  <div class="hgroup">
                    <h4><a href="company-detail.html">Facebook</a></h4>
                    <h5>Internet <a href="company-detail.html#open-positions"><span class="label label-info">6 jobs</span></a></h5>
                  </div>
                  <div class="action-btn">
                    <a class="btn btn-xs btn-gray" href="#">Edit</a>
                    <a class="btn btn-xs btn-danger" href="#">Delete</a>
                  </div>
                </header>
              </div>
            </div>
            <!-- END Company item -->


            <!-- Company item -->
            <div class="col-xs-12">
              <div class="item-block">
                <header>
                  <a href="company-detail.html"><img src="assets/img/logo-envato.png" alt=""></a>
                  <div class="hgroup">
                    <h4><a href="company-detail.html">Envato</a></h4>
                    <h5>Internet, Web Design, Web Development <a href="company-detail.html#open-positions"><span class="label label-info">2 jobs</span></a></h5>
                  </div>
                  <div class="action-btn">
                    <a class="btn btn-xs btn-gray" href="#">Edit</a>
                    <a class="btn btn-xs btn-danger" href="#">Delete</a>
                  </div>
                </header>
              </div>
            </div>
            <!-- END Company item -->


            <!-- Company item -->
            <div class="col-xs-12">
              <div class="item-block">
                <header>
                  <a href="company-detail.html"><img src="assets/img/logo-microsoft.jpg" alt=""></a>
                  <div class="hgroup">
                    <h4><a href="company-detail.html">Microsoft</a></h4>
                    <h5>Computer software and hardware <a href="company-detail.html#open-positions"><span class="label label-info">7 jobs</span></a></h5>
                  </div>
                  <div class="action-btn">
                    <a class="btn btn-xs btn-gray" href="#">Edit</a>
                    <a class="btn btn-xs btn-danger" href="#">Delete</a>
                  </div>
                </header>
              </div>
            </div>
            <!-- END Company item -->



          </div>
        </div>
      </section>
    </main>
    <!-- END Main container -->


    <!-- Site footer -->
    <footer class="site-footer">

      <!-- Top section -->
      <div class="container">
        <div class="row">
          <div class="col-sm-12 col-md-6">
            <h6>About</h6>
            <p class="text-justify">An employment website is a web site that deals specifically with employment or careers. Many employment websites are designed to allow employers to post job requirements for a position to be filled and are commonly known as job boards. Other employment sites offer employer reviews, career and job-search advice, and describe different job descriptions or employers. Through a job website a prospective employee can locate and fill out a job application.</p>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Company</h6>
            <ul class="footer-links">
              <li><a href="page-about.html">About us</a></li>
              <li><a href="page-typography.html">How it works</a></li>
              <li><a href="page-faq.html">Help center</a></li>
              <li><a href="page-typography.html">Privacy policy</a></li>
              <li><a href="page-contact.html">Contact us</a></li>
            </ul>
          </div>

          <div class="col-xs-6 col-md-3">
            <h6>Trendeing jobs</h6>
            <ul class="footer-links">
              <li><a href="job-list.html">Front-end developer</a></li>
              <li><a href="job-list.html">Android developer</a></li>
              <li><a href="job-list.html">iOS developer</a></li>
              <li><a href="job-list.html">Full stack developer</a></li>
              <li><a href="job-list.html">Project administrator</a></li>
            </ul>
          </div>
        </div>

        <hr>
      </div>
      <!-- END Top section -->

      <!-- Bottom section -->
      <div class="container">
        <div class="row">
          <div class="col-md-8 col-sm-6 col-xs-12">
            <p class="copyright-text">Copyrights &copy; 2016 All Rights Reserved by <a href="http://themeforest.net/user/shamsoft">ShaMSofT</a>.</p>
          </div>

          <div class="col-md-4 col-sm-6 col-xs-12">
            <ul class="social-icons">
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="dribbble" href="#"><i class="fa fa-dribbble"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
              <li><a class="instagram" href="#"><i class="fa fa-instagram"></i></a></li>
            </ul>
          </div>
        </div>
      </div>
      <!-- END Bottom section -->

    </footer>
    <!-- END Site footer -->


    <!-- Back to top button -->
    <a id="scroll-up" href="#"><i class="ti-angle-up"></i></a>
    <!-- END Back to top button -->

    <!-- Scripts -->
    <script src="assets/js/app.min.js"></script>
    <script src="assets/js/thejobs.js"></script>
    <script src="assets/js/custom.js"></script>

  </body>
</html>

employer/company/templates/company/company_add.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}TheJobs - Add company{% endblock %}
{% block content %}
<form class="login" method="POST" action="{% url 'new_company' %}" enctype="multipart/form-data">{% csrf_token %}{{ form.media }}

    <!-- Page header -->
    <header class="page-header">
        <div class="container page-name">
            <h1 class="text-center">Add your company</h1>
            <p class="lead text-center">Create a profile for your company and put it online.</p>
        </div>

        <div class="container">

            <div class="row">
                <div class="col-xs-12">
                    <div class="row">

                        <div class="col-xs-12 col-sm-4 col-lg-2">
                            <div class="form-group">
                                <input type="file" class="dropify" name="logo" accept="image/*" id="id_logo" data-default-file="{% static 'img/logo-default.png' %}">
                                <span class="help-block">A square logo</span>
                            </div>
                        </div>

                        <div class="col-xs-12 col-sm-8 col-lg-10">
                            <div class="form-group">
                                <input type="text" class="form-control input-lg" placeholder="Comapny name" name="name"
                                       maxlength="75" required="" id="id_name">
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control"
                                       placeholder="Headline (e.g. Internet and computer software)"
                                       name="field_of_activity" maxlength="75" required="" id="id_field_of_activity">
                            </div>

                            <div class="form-group">
                                <textarea class="form-control" cols="40" rows="10" placeholder="Short description"
                                          name="short_description" maxlength="400" required=""
                                          id="id_short_description"></textarea>
                            </div>
                        </div>

                    </div>
                </div>

                <div class="col-xs-12">
                    <div class="row">

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
                                <input type="text" class="form-control" placeholder="Location, e.g. Melon Park, CA"
                                       name="location" maxlength="75" required="" id="id_location">
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-users"></i></span>
                                <select class="form-control selectpicker" name="amount_of_workers"
                                        id="id_amount_of_workers">
                                    <option value="0 - 9">0 - 9</option>
                                    <option value="10 - 99" selected="">10 - 99</option>
                                    <option value="100 - 999">100 - 999</option>
                                    <option value="1,000 - 9,999">1,000 - 9,999</option>
                                    <option value="10,000 - 99,999">10,000 - 99,999</option>
                                    <option value="100,000 - 999,999">100,000 - 999,999</option>
                                </select>
                                <span class="input-group-addon">Employer</span>
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-globe"></i></span>
                                <input type="url" class="form-control" placeholder="Website address" name="website"
                                       maxlength="200" id="id_website">
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-birthday-cake"></i></span>
                                <input type="text" class="form-control" placeholder="Founded on, e.g. 2013"
                                       name="created_at" maxlength="4" required="" id="id_created_at">
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-phone"></i></span>
                                <input type="text" class="form-control" placeholder="Phone number" name="phone"
                                       maxlength="75" required="" id="id_phone">
                            </div>
                        </div>

                        <div class="form-group col-xs-12 col-sm-6 col-md-4">
                            <div class="input-group input-group-sm">
                                <span class="input-group-addon"><i class="fa fa-envelope"></i></span>
                                <input type="email" class="form-control" placeholder="Email address" name="email"
                                       maxlength="254" required="" id="id_email">
                            </div>
                        </div>

                    </div>
                </div>


            </div>

            <div class="button-group">
                <div class="action-buttons">
                    <div class="upload-button">
                        <button class="btn btn-block btn-primary">Choose a cover image</button>
                        <input id="cover_img_file" type="file">
                    </div>
                </div>
            </div>

        </div>
    </header>
    <!-- END Page header -->


    <!-- Main container -->
    <main>

        <!-- Social media -->
        <section>
            <div class="container">

                <header class="section-header">
                    <span>Get connected</span>
                    <h2>Social media</h2>
                </header>

                <div class="row">
                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-facebook"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="facebook_url"
                                       maxlength="200" id="id_facebook_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-google-plus"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="google_plus_url"
                                       maxlength="200" id="id_google_plus_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-dribbble"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="dribbble_url"
                                       maxlength="200" id="id_dribbble_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-pinterest"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="pinterest_url"
                                       maxlength="200" id="id_pinterest_url">
                            </div>
                        </div>
                    </div>

                    <div class="col-xs-12 col-sm-6">
                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-twitter"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="twitter_url"
                                       maxlength="200" id="id_twitter_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-github"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="github_url"
                                       maxlength="200" id="id_github_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-instagram"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="instagram_url"
                                       maxlength="200" id="id_instagram_url">
                            </div>
                        </div>

                        <div class="form-group">
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-youtube"></i></span>
                                <input type="url" class="form-control" placeholder="Profile URL" name="youtube_url"
                                       maxlength="200" id="id_youtube_url">
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </section>
        <!-- Social media -->

        <!-- Company detail -->
        <section class=" bg-alt">
            <div class="container">

                <header class="section-header">
                    <span>About</span>
                    <h2>Company detail</h2>
                    <p>Write about your company, culture, benefits of working there, etc.</p>
                </header>

                <textarea cols="40" id="id_company_detail" name="company_detail" rows="10" data-processed="0"
                          data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 1140, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}"
                          data-external-plugin-resources="[]" data-id="id_company_detail"
                          data-type="ckeditortype"></textarea>

            </div>
        </section>
        <!-- END Company detail -->


        <!-- Submit -->
        <section>
            <div class="container">
                <header class="section-header">
                    <span>Are you done?</span>
                    <h2>Submit it</h2>
                    <p>Please review your information once more and press the below button to put your company
                        online.</p>
                </header>

                <p class="text-center">
                    <button class="btn btn-success btn-xl btn-round">Submit your company</button>
                </p>

            </div>
        </section>
        <!-- END Submit -->


    </main>
    <!-- END Main container -->

</form>
{% endblock %}