core/urls.py
from django.urls import path

from .views import IndexView

urlpatterns = [
    path('', IndexView.as_view(), name='index_view'),
]

employer/job/urls.py
from django.urls import path

from employer.job.views import JobDetailView, JobUpdateView, JobDeleteView, JobCreateView, JobManage

urlpatterns = [
    path('<slug:company_slug>/<slug:slug>/', JobDetailView.as_view(), name='job_detail'),
    path('<slug:company>/<slug:slug>/update/', JobUpdateView.as_view(), name='job_update'),
    path('<slug:company>/<slug:slug>/delete/', JobDeleteView.as_view(), name='job_delete'),
    path('add/', JobCreateView.as_view(), name='job_add'),
    path('manage/', JobManage.as_view(), name='job_manage'),

]

employer/urls.py
from django.urls import path

from employer.views import JobDetailView, JobCreateView, JobUpdateView, JobManage, JobDeleteView

urlpatterns = [
    path('<slug:company>/<slug:slug>/', JobDetailView.as_view(), name='job_detail'),
    path('<slug:company>/<slug:slug>/update/', JobUpdateView.as_view(), name='job_update'),
    path('<slug:company>/<slug:slug>/delete/', JobDeleteView.as_view(), name='job_delete'),
    path('job-add/', JobCreateView.as_view(), name='job_add'),
    path('job-manage/', JobManage.as_view(), name='job_manage'),

]

jobsportal/urls.py
import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from core.views import UserSignupView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/signup/', UserSignupView.as_view(), name='account_signup'),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls')),
    path('company/', include('employer.company.urls')),
    path('job/', include('employer.job.urls')),
    path('resume/', include('jobseeker.resume.urls')),
    path('__debug__/', include(debug_toolbar.urls)),
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

employer/company/models.py
from ckeditor.fields import RichTextField
from django.db import models
from django.urls import reverse

from core.models import Userprofile


class Company(models.Model):
    amount = [
        ('0 - 9', '0 - 9'),
        ('10 - 99', '10 - 99'),
        ('100 - 999', '100 - 999'),
        ('1,000 - 9,999', '1,000 - 9,999'),
        ('10,000 - 99,999', '10,000 - 99,999'),
        ('100,000 - 999,999', '100,000 - 999,999'),

    ]

    def load_photo(self, file_name):
        file_type = file_name.split(".")[-1]
        file_name = ".".join(['{}/{}_logo', file_type])
        return file_name.format(
            self.name,
            self.name
        )

    name = models.CharField(max_length=75, verbose_name='Название компании')
    employer = models.OneToOneField(Userprofile, related_name='company', null=True, blank=True,
                                    on_delete=models.CASCADE, verbose_name='Работодатель')
    field_of_activity = models.CharField(max_length=75, verbose_name='Сфера деятельности')
    short_description = models.TextField(max_length=400, verbose_name='Краткое описание')
    location = models.CharField(max_length=75, verbose_name='Локация')
    logo = models.ImageField(upload_to=load_photo, default='Default/logo-default.png', null=True, blank=True, verbose_name='Лого')
    created_at = models.CharField(max_length=4, verbose_name='Год создания')
    amount_of_workers = models.CharField(max_length=20, choices=amount, default='10 - 99',
                                         verbose_name='Количество работников')
    phone = models.CharField(max_length=75, verbose_name='Номер телефона')
    website = models.URLField(null=True, blank=True, verbose_name='Адрес вебсайта')
    email = models.EmailField(verbose_name='Почта')
    slug = models.SlugField(max_length=75, unique=True)
    facebook_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на фейсбук компании')
    google_plus_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на гугл+ компании')
    dribbble_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на дрибл компании')
    pinterest_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на пинтерест компании')
    twitter_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на твиттер компании')
    github_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на гитхаб компании')
    instagram_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на инстаграм компании')
    youtube_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на ютуб компании')
    company_detail = RichTextField(blank=True, null=True, verbose_name='Полное описание')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('index_view')

employer/job/models.py
from django.db import models
from ckeditor.fields import RichTextField
from django.urls import reverse
from django.contrib.humanize.templatetags import humanize

from employer.company.models import Company


class Category(models.Model):
    title = models.CharField(max_length=75)
    slug = models.SlugField(max_length=75, unique=True)
    ordering = models.IntegerField(default=0)

    def __str__(self):
        return self.title

    class Meta:
        ordering = ['ordering']


class Job(models.Model):
    employment_types = [
        ('Full time', 'Full time'),
        ('Part time', 'Part time'),
        ('Internship', 'Internship'),
        ('Freelance', 'Freelance'),
        ('Remote', 'Remote'),

    ]

    degree = [
        ('Bachelor', 'Bachelor'),
        ('Master', 'Master'),
        ('Postdoc', 'Postdoc'),
        ('Doctor', 'Doctor'),
    ]

    title = models.CharField(max_length=75, verbose_name='Название работы')
    short_description = models.TextField(max_length=400, verbose_name='Краткое описание')
    category = models.ForeignKey(Category, related_name='jobs', on_delete=models.CASCADE)
    company = models.ForeignKey(Company, related_name='jobs', on_delete=models.CASCADE)
    application_url = models.URLField(null=True, blank=True, verbose_name='Ссылка на вакансию')
    location = models.CharField(max_length=75, verbose_name='Локация')
    type_of_employment = models.CharField(max_length=10, choices=employment_types, default='Full time',
                                          verbose_name='Вид трудоустройства')
    salary = models.CharField(max_length=75, verbose_name='Зарплата')
    working_hours = models.CharField(max_length=75, verbose_name='Часы работы')
    experience = models.CharField(max_length=75, verbose_name='Опыт работы')
    academic_degree = models.CharField(max_length=75, choices=degree, default='Bachelor', null=True, blank=True,
                                       verbose_name='Ученая степень')
    created_at = models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания объявления')
    slug = models.SlugField(max_length=75, unique=True)
    job_detail = RichTextField(blank=True, null=True, verbose_name='Полное описание')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('job_detail', kwargs={'company_slug': self.company.slug, 'slug': self.slug})

    def get_date(self):
        return humanize.naturaltime(self.created_at)

employer/company/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.views.generic import CreateView, DetailView

from employer.company.models import Company
from django.utils.text import slugify
from django.db import IntegrityError

from employer.job.models import Job
from django.core.exceptions import ObjectDoesNotExist


class CompanyCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'company/company_add.html'
    model = Company
    fields = ['name', 'field_of_activity', 'short_description', 'logo', 'location', 'created_at', 'amount_of_workers',
              'phone', 'website', 'email', 'facebook_url', 'google_plus_url', 'dribbble_url', 'pinterest_url',
              'twitter_url', 'github_url', 'instagram_url', 'youtube_url', 'company_detail']

    def form_valid(self, form):
        form.instance.employer = self.request.user.userprofile
        try:
            form.instance.slug = slugify(form.instance.name)
            return super().form_valid(form)
        except IntegrityError:
            latest_id = form.instance.__class__.objects.last().pk
            form.instance.slug = slugify(f'{form.instance.name}-{latest_id}')
            return super().form_valid(form)

    def test_func(self):
        """ Access is allowed only for Employers without any company """
        user_is_employer = self.request.user.userprofile.is_employer
        self.without_company = None
        if user_is_employer:
            try:
                self.request.user.userprofile.company
            except ObjectDoesNotExist:
                self.without_company = True
            else:
                self.without_company = False
        user = user_is_employer and self.without_company
        return user


class CompanyDetailView(DetailView):
    model = Company
    template_name = 'company/company_detail.html'
    slug_field = 'slug'
    context_object_name = 'company'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['company_jobs'] = Job.objects.filter(company=self.object).order_by('-created_at')[:5]
        return context

employer/job/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.shortcuts import get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView
from django.db import IntegrityError

from django.utils.text import slugify

from employer.job.models import Job, Category


class JobDetailView(DetailView):
    model = Job
    slug_field = 'slug'
    template_name = 'job/job_detail.html'
    context_object_name = 'job'


class JobManage(ListView):
    model = Job
    template_name = 'job/job_manage.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        queryset = Job.objects.filter(company=self.request.user.userprofile.company).select_related('company')
        return queryset


class JobCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'job/job_add.html'
    model = Job
    fields = ['title', 'short_description', 'category', 'application_url', 'location', 'type_of_employment', 'salary',
              'working_hours', 'experience', 'academic_degree', 'job_detail']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()
        return context

    def form_valid(self, form):
        form.instance.company = self.request.user.userprofile.company
        try:
            form.instance.slug = slugify(form.instance.title)
            return super().form_valid(form)
        except IntegrityError:
            latest_id = form.instance.__class__.objects.last().pk
            form.instance.slug = slugify(f'{form.instance.title}-{latest_id}')
            return super().form_valid(form)

    def test_func(self):
        user = self.request.user.userprofile.is_employer and self.request.user.userprofile.company
        return user


class JobUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'job/job_update.html'
    model = Job
    slug_field = 'slug'
    fields = ['title', 'short_description', 'category', 'application_url', 'location', 'type_of_employment', 'salary',
              'working_hours', 'experience', 'academic_degree', 'job_detail']

    def test_func(self):
        obj = self.get_object()
        user = self.request.user == obj.company.employer.user
        return user


class JobDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Job
    success_url = reverse_lazy('index_view')
    template_name = 'job/job_delete_confirmation.html'

    def test_func(self):
        obj = self.get_object()
        user = self.request.user == obj.company.employer.user
        return user

employer/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.urls import reverse_lazy
from django.views.generic import DetailView, CreateView, UpdateView, DeleteView, ListView

from employer.models import Job
from django.utils.text import slugify


class JobDetailView(DetailView):
    model = Job
    slug_field = 'slug'
    template_name = 'employer/job_detail.html'
    context_object_name = 'job'


class JobCreateView(LoginRequiredMixin, UserPassesTestMixin, CreateView):
    template_name = 'employer/job_add.html'
    model = Job
    fields = ['title', 'short_description', 'category', 'application_url', 'location', 'type_of_employment', 'salary',
              'working_hours', 'experience', 'academic_degree', 'job_detail']

    def form_valid(self, form):
        form.instance.company = self.request.user.userprofile.company
        form.instance.slug = slugify(form.instance.title)
        return super().form_valid(form)

    def test_func(self):
        user = self.request.user.userprofile.is_employer and self.request.user.userprofile.company
        return user


class JobUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    template_name = 'employer/job_update.html'
    model = Job
    slug_field = 'slug'
    fields = ['title', 'short_description', 'category', 'application_url', 'location', 'type_of_employment', 'salary',
              'working_hours', 'experience', 'academic_degree', 'job_detail']

    def test_func(self):
        obj = self.get_object()
        user = self.request.user == obj.company.employer.user
        return user


class JobDeleteView(DeleteView):
    model = Job
    success_url = reverse_lazy('index_view')
    template_name = 'employer/job_delete_confirmation.html'


class JobManage(LoginRequiredMixin, ListView):
    model = Job
    template_name = 'employer/job_manage.html'
    context_object_name = 'jobs'

    def get_queryset(self):
        queryset = Job.objects.filter(company=self.request.user.userprofile.company).select_related('company')
        return queryset

employer/templates/employer/job_add.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}TheJobs - Add job{% endblock %}
{% block content %}
<!-- Page header -->
<form class="login" method="POST" action="{% url 'job_add' %}">{% csrf_token %}{{ form.media }}
<header class="page-header">
    <div class="container page-name">
        <h1 class="text-center">Add a new job</h1>
        <p class="lead text-center">Create a new vacancy for your company and put it online.</p>
    </div>

    <div class="container">

            <div class="row">
                <div class="form-group col-xs-12 col-sm-6">
                    <input type="text" name="title" class="form-control input-lg" maxlength="75"
                           placeholder="Job title, e.g. Front-end developer" required="" id="id_title">
                </div>

                <div class="form-group col-xs-12 col-sm-6">
                    <select class="form-control selectpicker" name="category" required="" id="id_category">
                        <option value="" selected="">Select category</option>
                        <option value="1">Technology</option>
                    </select>
                    <a class="help-block" href="company-add.html">Add new category</a>
                </div>

                <div class="form-group col-xs-12">
                <textarea class="form-control" name="short_description" rows="3" maxlength="400"
                          placeholder="Short description" required="" id="id_short_description"></textarea>
                </div>

                <div class="form-group col-xs-12">
                    <input type="url" class="form-control" name="application_url" placeholder="Application URL"
                           maxlength="200" id="id_application_url">
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-map-marker"></i></span>
                        <input type="text" class="form-control" placeholder="Location, e.g. Melon Park, CA"
                               name="location"
                               maxlength="75" required="" id="id_location">
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-briefcase"></i></span>
                        <select class="form-control selectpicker" name="type_of_employment" id="id_type_of_employment">
                            <option value="Full time" selected="">Full time</option>
                            <option value="Part time">Part time</option>
                            <option value="Internship">Internship</option>
                            <option value="Freelance">Freelance</option>
                            <option value="Remote">Remote</option>
                        </select>
                    </div>
                </div>


                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-money"></i></span>
                        <input type="text" class="form-control" placeholder="Salary" name="salary" maxlength="75"
                               required="" id="id_salary">
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-clock-o"></i></span>
                        <input type="text" class="form-control" placeholder="Working hours, e.g. 40"
                               name="working_hours"
                               maxlength="75" required="" id="id_working_hours">
                        <span class="input-group-addon">hours / week</span>
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-flask"></i></span>
                        <input type="text" class="form-control" placeholder="Experience, e.g. 5" name="experience"
                               maxlength="75" required="" id="id_experience">
                        <span class="input-group-addon">Years</span>
                    </div>
                </div>

                <div class="form-group col-xs-12 col-sm-6 col-md-4">
                    <div class="input-group input-group-sm">
                        <span class="input-group-addon"><i class="fa fa-certificate"></i></span>
                        <select class="form-control selectpicker" name="academic_degree" id="id_academic_degree"
                                multiple>
                            <option value="" selected="">---------</option>
                            <option value="Bachelor">Bachelor</option>
                            <option value="Master">Master</option>
                            <option value="Postdoc">Postdoc</option>
                            <option value="Doctor">Doctor</option>
                        </select>
                    </div>
                </div>


            </div>

            <div class="button-group">
                <div class="action-buttons">
                    <div class="upload-button">
                        <button class="btn btn-block btn-primary">Choose a cover image</button>
                        <input id="cover_img_file" type="file">
                    </div>
                </div>
            </div>

    </div>
</header>
<!-- END Page header -->


<!-- Main container -->
<main>


    <!-- Job detail -->
    <section>
        <div class="container">

            <header class="section-header">
                <span>Description</span>
                <h2>Job detail</h2>
                <p>Write about your company, job description, skills required, benefits, etc.</p>
            </header>

            <textarea cols="40" id="id_job_detail" name="job_detail" rows="10" data-processed="0"
                      data-config="{&quot;skin&quot;: &quot;moono-lisa&quot;, &quot;toolbar_Basic&quot;: [[&quot;Source&quot;, &quot;-&quot;, &quot;Bold&quot;, &quot;Italic&quot;]], &quot;toolbar_Full&quot;: [[&quot;Styles&quot;, &quot;Format&quot;, &quot;Bold&quot;, &quot;Italic&quot;, &quot;Underline&quot;, &quot;Strike&quot;, &quot;SpellChecker&quot;, &quot;Undo&quot;, &quot;Redo&quot;], [&quot;Link&quot;, &quot;Unlink&quot;, &quot;Anchor&quot;], [&quot;Image&quot;, &quot;Flash&quot;, &quot;Table&quot;, &quot;HorizontalRule&quot;], [&quot;TextColor&quot;, &quot;BGColor&quot;], [&quot;Smiley&quot;, &quot;SpecialChar&quot;], [&quot;Source&quot;]], &quot;toolbar&quot;: &quot;Full&quot;, &quot;height&quot;: 291, &quot;width&quot;: 835, &quot;filebrowserWindowWidth&quot;: 940, &quot;filebrowserWindowHeight&quot;: 725, &quot;language&quot;: &quot;en-us&quot;}"
                      data-external-plugin-resources="[]" data-id="id_job_detail" data-type="ckeditortype"></textarea>

        </div>
    </section>
    <!-- END Job detail -->


    <!-- Submit -->
    <section class="bg-alt">
        <div class="container">
            <header class="section-header">
                <span>Are you done?</span>
                <h2>Submit Job</h2>
                <p>Please review your information once more and press the below button to put your job online.</p>
            </header>

            <p class="text-center">
                <button class="btn btn-success btn-xl btn-round" type="submit">Submit your job</button>
            </p>

        </div>
    </section>
    <!-- END Submit -->
</main>
</form>
<!-- END Main container -->
{% endblock %}

employer/templates/employer/job_detail.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}The JobsPortal {% endblock %}
{% block content %}
<!-- Page header -->
    <header class="page-header bg-img size-lg" style="background-image: url({% static 'img/bg-banner2.jpg' %})">
      <div class="container">
        <div class="header-detail">
          <img class="logo" src="{{ job.company.logo.url }}" alt="">
          <div class="hgroup">
            <h1>{{ job.title }}</h1>
            <h3><a href="#">{{ job.company }}</a></h3>
          </div>
          <time datetime="2016-03-03 20:00">{{ job.get_date }}</time>
          <hr>
          <p class="lead">You will help Google build next-generation web applications like Gmail, Google Docs, Google Analytics, and the Google eBookstore and eBook readers. As a Front End Engineer at Google, you will specialize in building responsive and elegant web UIs with AJAX and similar technologies. You may design or work on frameworks for building scalable frontend applications. We are looking for engineers who are passionate about and have experience building leading-edge user experience, including dynamic consumer experiences.</p>

          <ul class="details cols-3">
            <li>
              <i class="fa fa-map-marker"></i>
              <span>{{ job.location }}</span>
            </li>

            <li>
              <i class="fa fa-briefcase"></i>
              <span>{{ job.type_of_employment }}</span>
            </li>

            <li>
              <i class="fa fa-money"></i>
              <span>{{ job.salary }}</span>
            </li>

            <li>
              <i class="fa fa-clock-o"></i>
              <span>{{ job.working_hours }}</span>
            </li>

            <li>
              <i class="fa fa-flask"></i>
              <span>{{ job.experience }}</span>
            </li>

            <li>
              <i class="fa fa-certificate"></i>
              <a href="#">{{ job.academic_degree }}</a>
            </li>
          </ul>

          <div class="button-group">
            <ul class="social-icons">
              <li class="title">Share on</li>
              <li><a class="facebook" href="#"><i class="fa fa-facebook"></i></a></li>
              <li><a class="google-plus" href="#"><i class="fa fa-google-plus"></i></a></li>
              <li><a class="twitter" href="#"><i class="fa fa-twitter"></i></a></li>
              <li><a class="linkedin" href="#"><i class="fa fa-linkedin"></i></a></li>
            </ul>

            <div class="action-buttons">
              <a class="btn btn-primary" href="#">Apply with linkedin</a>
              <a class="btn btn-success" href="job-apply.html">Apply now</a>
            </div>
          </div>

        </div>
      </div>
    </header>
    <!-- END Page header -->


    <!-- Main container -->
    <main>

      <!-- Job detail -->
      <section>
        <div class="container">
          {{ job.job_detail | safe }}
        </div>
      </section>
      <!-- END Job detail -->

    </main>
    <!-- END Main container -->
{% endblock %}

employer/templates/employer/job_manage.html
{% extends 'core/base.html' %}
{% load static %}
{% block title %}The JobsPortal {% endblock %}
{% block content %}
<!-- Page header -->
    <header class="page-header bg-img size-lg" style="background-image: url(assets/img/bg-banner1.jpg)">
      <div class="container no-shadow">
        <h1 class="text-center">Manage jobs</h1>
        <p class="lead text-center">Here's the list of your posted jobs. You can edit or delete them, or even add a new one.</p>
      </div>
    </header>
    <!-- END Page header -->


    <!-- Main container -->
    <main>
      <section class="no-padding-top bg-alt">
        <div class="container">
          <div class="row">

            <div class="col-xs-12 text-right">
              <br>
              <a class="btn btn-primary btn-sm" href="job-add.html">Add new job</a>
            </div>

          {% for job in jobs %}
            <!-- Job detail -->
            <div class="col-xs-12">
              <div class="item-block">
                <header>
                  <a href="{{ job.get_absolute_url }}"><img src="{{ job.company.logo.url }}" alt=""></a>
                  <div class="hgroup">
                    <h4><a href="{{ job.get_absolute_url }}">{{ job.title }}</a></h4>
                    <h5><a href="company-detail.html">{{ job.company }}</a></h5>
                  </div>
                  <div class="header-meta">
                    <span class="location">{{ job.location }}</span>
                    <time datetime="2016-03-10 20:00">34 min ago</time>
                  </div>
                </header>

                <footer>
                  <p class="status"><strong>Status:</strong> Pending approval</p>

                  <div class="action-btn">
                    <a class="btn btn-xs btn-gray" href="{% url 'job_update' job.company.slug job.slug %}">Edit</a>
                    <a class="btn btn-xs btn-danger" href="{% url 'job_delete' job.company.slug job.slug %}">Delete</a>
                  </div>
                </footer>
              </div>
            </div>
            {% endfor %}
            <!-- END Job detail -->
          </div>
        </div>
      </section>
    </main>
    <!-- END Main container -->
{% endblock %}

